utils: fix aiohttp.ClientSession created with a different loop
The ClientSession was created by SchemaRegistrySerializer, during
_init_kafka_rest which is itself called by KafkaRest.__init__, in the sync
context of main and outside of aiohttp.web.run_app.

This fixes this error that appears when using aiohttp >= 3.8.0 :
```
  File ".../karapace/karapace/serialization.py", line 144, in get_schema_for_subject
    schema_id, schema = await self.registry_client.get_latest_schema(subject)
  File ".../karapace/karapace/serialization.py", line 83, in get_latest_schema
    result = await self.client.get(f"subjects/{quote(subject)}/versions/latest")
  File ".../karapace/karapace/utils.py", line 109, in get
    async with self.client.get(
  File ".../karapace/venv/lib64/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File ".../karapace/venv/lib64/python3.9/site-packages/aiohttp/client.py", line 466, in _request
    with timer:
  File ".../karapace/venv/lib64/python3.9/site-packages/aiohttp/helpers.py", line 701, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
```
https://github.com/aio-libs/aiohttp/blob/f6334e2b4881b9870edcaaa20e9282c4e9dc70f1/aiohttp/client.py#L423-L425
https://github.com/aio-libs/aiohttp/blob/f6334e2b4881b9870edcaaa20e9282c4e9dc70f1/aiohttp/helpers.py#L677-L683