rest: fix aiokafka.AIOKafkaProducer loop AssertionError
Attempting to use the loop created during _init_kafka_rest,
which is itself called by KafkaRest.__init__, in the sync context
of main and outside of aiohttp.web.run_app does not play
well with aiokafka >= 0.7.0

```
Traceback (most recent call last):
   File "/usr/lib/python3.9/site-packages/karapace/kafka_rest_apis/__init__.py", line 192, in _create_async_producer
     await p.start()
   File "/usr/lib/python3.9/site-packages/aiokafka/producer/producer.py", line 286, in start
     assert self._loop is asyncio.get_event_loop(), (
 AssertionError: Please create objects with the same loop as running with
 ```

 https://github.com/aio-libs/aiokafka/blob/f7f55b19b43b084edc844c3531a570d233d37912/aiokafka/producer/producer.py#L284-L289